### PR TITLE
Lab1 files add

### PR DESCRIPTION
**Pull request by MishaKoval**

### CODE REVIEW

**Review by katetushkan — APPROVED** [review]
That's 10. Topic for the 2nd Block, pls.

**Comment by MishaKoval** [comment]
Это нужно из предложенных выбрать?

**Comment by katetushkan** [comment]
Eto nuzhno pochitat' doc. Everything is written there. U can choose from the list or provided ur own topic.

**Comment by MishaKoval** [comment]
Nu togda pust budet Managing tools )

**Pull request closed without merging**
